// The content of this file was generated by IBM Cloud
// Do not modify it as it might get overridden
module.exports = function(app, server){
    require('./public')(app);
    require('./health')(app);
<<<<<<< HEAD
    require('./Postgresql')(app, server);
=======
>>>>>>> 57ee2bde122c797ab597c33a6b1d27ec24c7f1cc
};
